// Generated from core-pipeline/stages/lib/keyword-canon/page_taxonomy.json
// (version 1.1): 49 page types, 190 sub-types. Regenerate
// rather than edit by hand when the taxonomy changes.

export const PAGE_TYPE_CHOICES = [
  "Progress Note",
  "Laboratory Data",
  "Radiology Report",
  "Patient Demographics",
  "Discharge Summary",
  "Forms",
  "Clinical Summary",
  "Orders",
  "Cardiac Report",
  "Operative Report",
  "Discharge Instructions",
  "Telephone Encounter",
  "Functional Assessment",
  "Messages",
  "Administration",
  "Triage Note",
  "Medication List",
  "Nursing Note",
  "Billing / Invoice",
  "Echocardiogram Report",
  "Pathology Report",
  "EKG / ECG Tracing",
  "Gastroenterology / GI",
  "Patient Education",
  "Procedure Note",
  "Ophthalmology Note",
  "Referral & Authorization",
  "Psychiatric Evaluation",
  "Other Evaluation",
  "Emergency Note",
  "Allergies Report",
  "Therapy",
  "Immunizations",
  "ENT Note",
  "Wound & Infection Care",
  "Interim Summary",
  "ICU Note",
  "Nuclear Medicine Report",
  "Vascular Studies",
  "Occupational & Physical Exams",
  "Annual Assessments",
  "Obstetrics & Women's Health",
  "Neurology",
  "Nephrology",
  "Oncology",
  "Respiratory",
  "Sleep Study",
  "Pain & Palliative Note",
  "Implants",
] as const;

/** Every sub-type. Laboratory Data and Radiology Report are also the
 * sub-types of a lab or radiology page inside a Progress Note. */
export const PAGE_SUBTYPE_CHOICES = [
  "Progress Note",
  "Summary",
  "Visit Diagnosis",
  "Physician Note",
  "Problem List",
  "Plan of Care",
  "Signature page",
  "Office Visit",
  "F2F Evaluation Note",
  "Social History",
  "Laboratory Data",
  "Chemistry",
  "Hematology",
  "Microbiology",
  "Urinalysis",
  "Glucose report",
  "Allergy testing report",
  "Genetic Test Report",
  "FISH Report",
  "Radiology Report",
  "Bone Density (DEXA) Report",
  "X Ray Report",
  "CT Scan Report",
  "Ultrasound Report",
  "Tomography",
  "MRI Report",
  "MR brain report",
  "Sonogram report",
  "Patient Demographics",
  "Face Sheet",
  "Patient Information",
  "Patient Registration",
  "Discharge Summary",
  "Depart Note",
  "Transfer Summary",
  "Short Stay Summary",
  "Final Case Summary",
  "Principal Diagnosis",
  "Forms",
  "Consent Form",
  "Questionnaire",
  "Checklist",
  "Mini-Mental State Exam",
  "HIPAA Form",
  "Clinical Summary",
  "Orders",
  "Medication Orders",
  "Post Operative Orders",
  "Pre Operative Orders",
  "Protocols",
  "Cardiac Report",
  "EKG Report (12-lead / routine)",
  "CT Angiography",
  "Stress Test",
  "Cardiac catheterization report",
  "Treadmill report",
  "Operative Report",
  "Pre Operative Evaluation",
  "Anaesthesia Report",
  "Operation Summary",
  "Phase Record",
  "Operation Note",
  "Post Operative Followup Note",
  "Discharge Instructions",
  "Telephone Encounter",
  "Phone Note",
  "Functional Assessment",
  "ADL/IADL flow sheet",
  "Messages",
  "Notice",
  "Letter",
  "Notification",
  "Ambulatory Correspondence",
  "Administration",
  "Index Page",
  "Appointments",
  "Triage Note",
  "ED Triage",
  "Medication List",
  "Prescription / Rx page",
  "Refill record",
  "Nursing Note",
  "Growth chart",
  "Billing / Invoice",
  "Invoice",
  "Echocardiogram Report",
  "Pathology Report",
  "Biopsy Report",
  "Tissue Report",
  "Cytology / molecular report",
  "Mohs surgery report",
  "EKG / ECG Tracing",
  "ECG Graph",
  "Holter monitor report",
  "Gastroenterology / GI",
  "Endoscopy report",
  "Colonoscopy / sigmoidoscopy report",
  "Esophageal manometry",
  "Patient Education",
  "Procedure Note",
  "Ophthalmology Note",
  "Retinal / Eye Report",
  "Laser procedure report",
  "Fundus photography",
  "Optometry note",
  "Lens Parameters",
  "Visual Evaluation",
  "Referral & Authorization",
  "Referral Request",
  "Referral authorization form",
  "Insurance Authorization Form",
  "Psychiatric Evaluation",
  "Initial psychiatric evaluation",
  "Psychiatric Note",
  "Behavioral health note",
  "Group Therapy Note",
  "Substance use treatment record",
  "Neurocognitive screening exam",
  "Other Evaluation",
  "Nutrition assessment",
  "Emergency Note",
  "Urgent care note",
  "EMS / ambulance report",
  "Allergies Report",
  "Therapy",
  "Physical Therapy",
  "Occupational Therapy",
  "Rehabilitation Plan",
  "Speech therapy note",
  "Chiropractic treatment note",
  "Acupuncture treatment record",
  "Immunizations",
  "Immunization list",
  "Vaccine Record",
  "ENT Note",
  "Audiology / hearing report",
  "Laryngoscopy report",
  "Videonystagmography (VNG)",
  "Wound & Infection Care",
  "Wound care note",
  "Burn treatment record",
  "Infection control note",
  "Interim Summary",
  "ICU Note",
  "Nuclear Medicine Report",
  "SPECT report",
  "Myocardial perfusion imaging",
  "Vascular Studies",
  "Doppler-duplex",
  "Carotid duplex",
  "Lower / upper extremity Doppler-duplex",
  "Plethysmography report",
  "Occupational & Physical Exams",
  "Occupational health record",
  "Work injury evaluation",
  "Sports physical exam",
  "Annual Assessments",
  "Medicare annual wellness visit",
  "Staying Healthy Assessment",
  "HouseCalls visit summary",
  "Obstetrics & Women's Health",
  "Prenatal record / ACOG form",
  "Antepartum record",
  "Postpartum visit / exam",
  "Pap smear report",
  "Colposcopy exam",
  "Neurology",
  "EEG / neurophysiology report",
  "EMG report",
  "Sudoscan",
  "DPN results",
  "Nephrology",
  "Dialysis Note",
  "Oncology",
  "Radiation therapy record",
  "Chemotherapy administration record",
  "Infusion therapy note",
  "Blood transfusion record",
  "Respiratory",
  "Oximetry report",
  "Pulmonary function test / spirometry",
  "Ventilator management record",
  "Sleep Study",
  "Polysomnography",
  "Split-night sleep study",
  "CPAP / BiPAP titration report",
  "Pain & Palliative Note",
  "Implants",
  "Pacemaker Report",
  "Device implant log",
] as const;
