export const PAGE_TYPE_CHOICES = [
  "Progress Note",
  "Discharge",
  "Obstetric",
  "Procedure",
  "Assessment / Screening",
  "Behavioral Health",
  "Care Plan",
  "Inpatient / Critical Care",
  "Specialty Consult",
  "Therapy / Rehab",
  "Ophthalmology",
  "Screening / Checklist",
  "Cardiac Diagnostic",
  "Neuro Diagnostic",
  "Pulmonary Function Test",
  "Pulmonary / Sleep",
  "Vascular / Holter",
  "Imaging",
  "Laboratory",
  "Nuclear Medicine",
  "Pathology",
  "Medication / Immunization",
  "Therapy Administration",
  "Consent / Authorization",
  "Orders / Requests",
  "Letter",
  "Patient Communication",
  "Administrative",
  "Demographics",
] as const;

export const PAGE_SUBTYPE_CHOICES = [
  "Progress Note",
  "Initial Psychiatric Evaluation",
  "Telephone Messages",
  "Any Type of Notice",
  "PAP / HPV Report",
  "Annual Wellness Visit",
  "Emergency / ED Visit",
  "Prenatal Records(ACOG Form/Prenatal Visit Flow chart/ Prenatal Flow/ Prenatal Form )",
  "Any Messages",
  "Depart Note",
  "Antepartum Record",
  "Application Form",
  "Depart Summary",
  "Postpartum/PP Exam/PP Visit",
  "Billing Page from the Doctor",
  "Discharge instructions",
  "Activity Evaluation",
  "Blood Glucose",
  "Discharge Medication",
  "All EYE exam report/records (OD or OS evidance)",
  "Bone Mineral Density (DEXA) Report",
  "Discharge Summary",
  "Ophthalmology Report or Records / Ocular Note",
  "Transfer Summary",
  "Optometry note/Visual field activity/retinopathy",
  "Chemistry Report",
  "Transition of care Summary",
  "Anesthesia Record",
  "Chest View",
  "Resumen de Alta / Resumen de Instruccion / Planificacion de Alta",
  "Annual Health Assessment",
  "Consent form",
  "Interim Summaries",
  "Consent/Authorization pages -all",
  "Discharge Note",
  "Any type of Letter",
  "Fluorescence in situ Hybridization (FISH)",
  "Transfer of Care Note",
  "Assessment notes/Forms/Report",
  "Lab Flow Sheet",
  "Cardiac Catheterization",
  "Lab Form",
  "Cardiology",
  "Laboratory Data",
  "Short Stay Summary",
  "Cardiovascular report",
  "Lab Requisition",
  "Occupational Therapy Discharge Note/summary",
  "(CC) Chief Complaint/(HPI) History of Present Illness/Physical exam",
  "Lab work (Blood, Cholesterol, etc.)",
  "Physical Therapy Discharge Note/Summary",
  "Colonoscopy/Sigmoidoscopy",
  "Mammograms / MG/ Mammo",
  "Interim Note",
  "Colposcopic Examination",
  "Medication List",
  "BH-OP Discharge",
  "Consultations / Consulta",
  "Microbiology",
  "Principal Diagnosis",
  "Cytology Report/Molecular Report",
  "Mini Mental examination",
  "Anesthesia Transfer of Care note",
  "Dermatology / Skin Test",
  "Patient Education",
  "Final Case Summary",
  "Echocardiogram / Transthoracic Echocardiography",
  "Plethysmography Report",
  "EEG Report/Neurophysiology Report",
  "Prothrombin time",
  "EKG /ECG graph",
  "Pulmonary function Test/ Spirometry",
  "Referral Authorization Form",
  "EMG Report",
  "Refill Record",
  "Encounter Form/visit",
  "social report",
  "Endoscopy",
  "Sonograms Report",
  "Established patient note",
  "Tomography",
  "Evaluation form",
  "Triage call",
  "Functional assessment",
  "Ultrasounds Report",
  "Gastroenterology (GI Procedure Note)(EGD Report)",
  "Urinalysis",
  "History & Physical",
  "All types of order",
  "Lower Extremity (Lower Extremity Doppler\\Duplex report) / Upper Extremity",
  "Order note",
  "Medical Status Visit form/Status visit",
  "Physician Order",
  "Myocardial perfusion",
  "Patient Instruction",
  "Nephrology",
  "Any Type of Request",
  "Neurology / EMG Note",
  "INR result/ INR (International Normalized Ratio) Value",
  "Nurses notes",
  "MR Brain Report",
  "Nutrition Assessment",
  "MRI",
  "Occupational Therapy",
  "CT Scans Report",
  "Office visits/followup Visits",
  "Prescriptions/RX Page",
  "Oncology",
  "Radiology Report",
  "Operative Report",
  "X-Ray Report (Foot Exam)",
  "Oximetry report/note",
  "Allergies report",
  "Pacemaker / Device monitor report",
  "Carotid Duplex Report",
  "All Doppler/Duplex Report(Example echo doppler report)",
  "Pathology Report/Tissue Report",
  "Esophageal Manometry",
  "Physical Therapy Assessment/Note",
  "Health Review sheet\\Health Maintenance Report",
  "Physician Notes",
  "Holter report",
  "Plan of Care",
  "ADL/IADL flow sheet (Activity of daily living)",
  "Procedure Note",
  "Ankle-Brachial Index (ABI)",
  "Check List",
  "Rehabilitation Daily Treatment Note",
  "Immunization List/ Vaccine / flu Shot",
  "Sleep Study /Polysomnography Report(PSG Report)",
  "Questionnaire(Stand Alone)",
  "SOAP Note (Subjective, Objective, Assessment, Plan)",
  "After Visit Summary",
  "Staying Healthy Assessment",
  "Stress Test / Exercise report / treadmill exercise report",
  "surgery report",
  "Problem List",
  "Treatment Plan Record",
  "Out Of Time Frame Records",
  "Triage Note/Report",
  "Invoice Page when Soruce is: Imaging Client Upload, Client Retrieval,Client FTP, RF Support, Remote Download/EMR",
  "Triage surgery report",
  "Patient summary-If Stand Alone",
  "Urgent Care Note",
  "Appointment Note",
  "Urology",
  "Appointment Summary",
  "Nuclear Medicine Report",
  "AMB - Correspondence",
  "Cytometry Report",
  "Clinical Diagnoses",
  "Telephone Encounter\\Visit\\Note\\Phone note",
  "Protocols",
  "Demographics",
  "Vaccination Administration Record",
  "Face sheet / Registration",
  "Immunization Consent",
  "Audiology / Hearing Report/Audiology Notes",
  "Allergy Testing Report",
  "Patient Summary-If received along with the Progress note,Office Visit/Notes",
  "Genetic Test Report",
  "Visit summary",
  "Insurance Authorization Note",
  "Initial office note",
  "Surgical Consent Form",
  "Occupational Therapy Daily Note",
  "Blood Transfusion Record",
  "Retinal Office Procedure Note",
  "Transfusion Consent",
  "Screening Test Record",
  "Inform Evaluation Visual",
  "Preventive Health Checklist",
  "Fundas Photography(EYE REPORT)",
  "Glucose Report",
  "Case History Update",
  "HIPAA Form",
  "Biopsy report/Pathology report",
  "Patient Portal Communication Summary",
  "Patient Encounter",
  "Discharge Notice",
  "Laryngoscopy Procedure Report",
  "Hematology",
  "Tissue Examination Report",
  "Molecular Diagnostics Test",
  "Therapy report",
  "Radiation Therapy Record",
  "Chemotherapy Administration Record",
  "Infusion Therapy Note",
  "Pain Management Note",
  "Palliative Care Note",
  "Hospice Care Record",
  "Critical Care Note",
  "ICU Flow Sheet",
  "Ventilator Management Record",
  "Respiratory Therapy Note",
  "Dialysis Treatment Record",
  "Hemodialysis Flow Sheet",
  "Peritoneal Dialysis Record",
  "Wound Care Note",
  "Burn Treatment Record",
  "Infection Control Note",
  "Genetic Counseling Note",
  "Sleep Clinic Note",
  "Behavioral Health Note",
  "Psychotherapy Session Note",
  "Substance Abuse Treatment Record",
  "Rehabilitation Plan",
  "Speech Therapy Note",
  "Chiropractic Treatment Note",
  "Acupuncture Treatment Record",
  "Home Health Visit Note",
  "Skilled Nursing Visit Note",
  "Case Management Note",
  "Care Coordination Note",
  "Utilization Review Note",
  "Preoperative Evaluation",
  "Postoperative Follow-up Note",
  "Anesthesia Pre-op Assessment",
  "Anesthesia Post-op Note",
  "Implant Record",
  "Device Implant Log",
  "Emergency Medical Services (EMS) Report",
  "Occupational Health Record",
  "Work Injury Evaluation",
  "Fitness for Duty Evaluation",
  "School Physical Form",
  "Sports Physical Examination",
  "Travel Medicine Consultation",
  "Chronic Disease Management Note",
  "Hypertension Follow-up Note",
  "Cardiac Rehabilitation Note",
  "patient care Report",
  "Clinical Summary",
  "Treadmill Report",
  "Face to Face Evaluation Note",
  "Lens Parameters",
  "Neurocognitive Screening Examination",
  "Split Night Report",
  "Group Note",
  "SPECT Report",
  "Event Report",
  "Housecalls Visit Summary",
  "Videonystagmography",
  "Device Specialist notes",
  "Titration Report",
  "Sural Nerve Conduction Study",
  "Visual Field interpretation",
  "MOHS Report",
  "Client note",
  "Sudoscan Report",
  "DPN Results",
  "Visit Report",
  "Discharge Report",
] as const;
